%% drgCaImAn_warp_ROIs.m
%
% Needs as an input the ouput file from drgCaImAn_script
%
close all
clear all



%% Get the raw and inferred traces generated by drgCaimAn_script for the tiff files whose ROIs will be replaced by 
% warped ROIs from the reference tiffs
[fnameca,pnameca,nCancel] = uigetfile({'*CalmAn.mat'},'Select the output file from CaimAn for the tiff images that will get new ROIs ...');
if nCancel
    inputPath = [pnameca,fnameca];
    pnameStart = pnameca;
    %save('timeCorr_cfg.mat','pnameStart','-append');
else
    error('Cancelled')
end


CaimAn_name=[pnameca fnameca];

fnameca1=fnameca;

load(CaimAn_name)

CaImAn_name1=[CaimAn_name(1:end-11) '.tif'];
 
Yr1=Yr;
C_or1=C_or;
b21=b2;
f21=f2;
Cn1=Cn;
options1=options;
CaImAn_name_out=[CaimAn_name(1:end-4) '_warped.mat'];

thr = 0.95;
d1 = options.d1;
d2 = options.d2;

%Draw the ROIs for the first image
figure(1)
cla
imagesc(2*Cn); axis equal; axis tight; axis off; hold on;
Cn1=2*Cn;
A_or1=A_or;

%Find the number of ROIs
szA_or=size(A_or);

for i=1:szA_or(2)
    A_temp = full(reshape(A_or(:,i),d1,d2));
    A_temp = medfilt2(A_temp,[3,3]);
    A_temp = A_temp(:);
    [temp,ind] = sort(A_temp(:).^2,'ascend');
    temp =  cumsum(temp);
    ff = find(temp > (1-thr)*temp(end),1,'first');
    if ~isempty(ff)
        [~,ww] = contour(reshape(A_temp,d1,d2),[0,0]+A_temp(ind(ff)),'LineColor','k');
        ww.LineWidth = 2;
    end
end

title(['ROIs for ' fnameca])
fnameca1=fnameca;

figure(2)
cla
imagesc(2*Cn); axis equal; axis tight; axis off; hold on;
title([fnameca ' reference tif'])


[fnameca,pnameca,nCancel] = uigetfile({'*CalmAn.mat'},'Select the output file from CaimAn for the refrence images that will provide ROIs...');
if nCancel
    inputPath = [pnameca,fnameca];
    pnameStart = pnameca;
    %save('timeCorr_cfg.mat','pnameStart','-append');
else
    error('Cancelled')
end


CaimAn_name=[pnameca fnameca];


load(CaimAn_name)

thr = 0.95;
d1 = options.d1;
d2 = options.d2;

%Draw the ROIs for the first image
figure(3)
cla
imagesc(2*Cn); axis equal; axis tight; axis off; hold on;
Cn2=2*Cn;

%Find the number of ROIs
szA_or=size(A_or);

for i=1:szA_or(2)
    A_temp = full(reshape(A_or(:,i),d1,d2));
    A_temp = medfilt2(A_temp,[3,3]);
    A_temp = A_temp(:);
    [temp,ind] = sort(A_temp(:).^2,'ascend');
    temp =  cumsum(temp);
    ff = find(temp > (1-thr)*temp(end),1,'first');
    if ~isempty(ff)
        [~,ww] = contour(reshape(A_temp,d1,d2),[0,0]+A_temp(ind(ff)),'LineColor','k');
        ww.LineWidth = 2;
    end
end

title(['ROIs for ' fnameca])

%Draw the ROIs for the first image
figure(4)
cla
imagesc(2*Cn); axis equal; axis tight; axis off; hold on;
title([fnameca ' reference tif'])


figure(5)
imshowpair(Cn2, Cn1,'Scaling','joint')
title('Overalay of images')

%Register the second image to the first image
%I am using multimodal becasue the images have different brightness
[optimizer, metric] = imregconfig('multimodal');
tform = imregtform(Cn2, Cn1, 'rigid', optimizer, metric);
Cn2_warp = imwarp(Cn2,tform,'OutputView',imref2d(size(Cn1)));

figure(6)
imshowpair(Cn2_warp, Cn1,'Scaling','joint')
title('Overalay of images after warp')

%Now let's register the A_or ROIs
figure(7)
cla
imagesc(2*Cn1); axis equal; axis tight; axis off; hold on;
for i=1:szA_or(2)
    A_temp = full(reshape(A_or(:,i),d1,d2));
    A_temp = imwarp(A_temp,tform,'OutputView',imref2d(size(Cn1)));
    A_warp = A_temp;
    A_or1(:,i)=A_warp(:);
    A_temp = medfilt2(A_temp,[3,3]);
    A_temp = A_temp(:);
    [temp,ind] = sort(A_temp(:).^2,'ascend');
    temp =  cumsum(temp);
    ff = find(temp > (1-thr)*temp(end),1,'first');
    if ~isempty(ff)
        [~,ww] = contour(reshape(A_temp,d1,d2),[0,0]+A_temp(ind(ff)),'LineColor','k');
        ww.LineWidth = 2;
    end
end


title(['ROIs from reference image overlaid on ' fnameca1])

%Update temporal components
%I was lost here, but Andrea Giovannucci and Eftychios Pnevmatikakis
%helped!
[C_upd] = update_temporal_components_fast(CaImAn_name1,A_or1);

%Constrained update of spatial components is used to compute b2 
% options1.spatial_method='constrained';
% [A_upd,b2,C_upd] = update_spatial_components(Yr1,C_upd,f21,A_or1,[],options1);
% %Should I use A_upd?
%Answer = No, what we want is A_or1 setup from the reference tiff images
% figure(8)
% cla
% imagesc(2*Cn1); axis equal; axis tight; axis off; hold on;
% szA_upd=size(A_upd);
% for i=1:szA_upd(2)
%     A_temp = full(reshape(A_upd(:,i),d1,d2));
%     A_temp = medfilt2(A_temp,[3,3]);
%     A_temp = A_temp(:);
%     [temp,ind] = sort(A_temp(:).^2,'ascend');
%     temp =  cumsum(temp);
%     ff = find(temp > (1-thr)*temp(end),1,'first');
%     if ~isempty(ff)
%         [~,ww] = contour(reshape(A_temp,d1,d2),[0,0]+A_temp(ind(ff)),'LineColor','k');
%         ww.LineWidth = 2;
%     end
% end

% %Save the registered file
% A_or=A_or1;
% 
% %Should I use C_or1 or C_upd?
% % C_or=C_upd;
% C_or=C_or1;
% 
% Cn=Cn1;
% Yr=Yr1;

%Test the traces
[raw,inferred]=drgGetCAtraces(Yr1,A_or1,C_upd,b21,f21,Cn1,options1);

% In order to understand what these variables are take a look at
% plot_components_GUI.m under CaImAn-MATLAB/utilities
% CaImAn calls ROIs "components"
% Yr hs the 6000 images in a vector of 65536 pixels
% A_or has the image of each component e.g. 65536x158 double for 256x256
% images of 85 components
% C_or these are the inferred traces for each component
% b2 are one or two images
% f2 are one or two traces
% Cn is the correlation image e.g. 256x256


traces=raw;

figure(9)
plot(traces(1,:))

%Save the registered file
Yr=Yr1;
A_or=A_or1;
C_or=C_upd;
b2=b21;
f2=f21;
Cn=Cn1;
options=options1;

%Save the results
save(CaImAn_name_out,'Yr','A_or','C_or','b2','f2','Cn','options')

pffft=1;



