%% drgCaImAn_dropc_plot.m
%
% Needs as an input the ouput file from drgCaImAn_dropc
%
close all
clear all


% Get the raw and inferred traces generated by drgCaimAn_script
[fnameca,pnameca,nCancel] = uigetfile({'*_pre_per.mat'},'Select the output file from CaimAn...');
if nCancel
    inputPath = [pnameca,fnameca];
    pnameStart = pnameca;
    %save('timeCorr_cfg.mat','pnameStart','-append');
else
    error('Cancelled')
end


CaimAn_dropc_name=[pnameca fnameca];

load(CaimAn_dropc_name)

try
    close 1
catch
end

hFig1 = figure(1);
set(hFig1, 'units','normalized','position',[.05 .1 .85 .8])

hold on
 
% Determine the y spacing of the traces
y_shift=1.2*(prctile(traces(:),95)-prctile(traces(:),5));

%Plot the event lines

%For S+ and S- plot odor on and reinforcement
for epoch=1:handles.dropcData.epochIndex
    %Epoch 2 is odor on, 3 is odor off
    plot_epoch=(handles.dropcData.epochEvent(epoch)==2)||(handles.dropcData.epochEvent(epoch)==3);
    if plot_epoch
        if handles.dropcData.epochTypeOfOdor(epoch)==handles.dropcProg.splusOdor
            plot([handles.dropcData.epochTime(epoch) handles.dropcData.epochTime(epoch)], [0 (no_traces+2)*y_shift],...
                '-r','LineWidth',1)
        else
            plot([handles.dropcData.epochTime(epoch) handles.dropcData.epochTime(epoch)], [0 (no_traces+2)*y_shift],...
                '-b','LineWidth',1)
        end
    end
end


%Plot the licks recorded by the INTAN (adc_in)
pct998=prctile(adc_in,99.8);
pct1=prctile(adc_in,1);
norm_fact=0.8*y_shift/(pct998-pct1);

plot(time_rhd(time_rhd>0),adc_in(time_rhd>0)*norm_fact)

%Plot the traces
dt=1/options.fr;
time=[1:no_images]*dt;
for trNo=1:no_traces
    plot(time,traces(trNo,:)+y_shift*trNo,'-k','LineWidth',1)
end

ylim([-y_shift*0.2 (no_traces+2)*y_shift])
xlabel('time (s)')
ylabel('deltaF/F')
title(fnameca(1:end-4))

