% drgCaImAn_rainbow generates pseudocolor plots of the deltaF/F traces per
% ROI
% Needs as an input the ouput file from drgCaImAn_dropc
%
close all
clear all

%% choices
plot_raw=1;

%Choose dropc program

% 1 dropc_nsampler_piriform

% 2 dropcspm_hf before 2/23/2018

% 3 dropcspm_hf after 2/24/2018
%
%  handles.dropcData.epochEvent
% 1 - FV on
% 2 - odor on
% 3 - odor off
% 4 - reinforcement on
% 5 - reinforcement off
% 6 - Hit
% 7 - Miss
% 8 - FA
% 9 - CR

dropc_program=3; 

%If this variable is included you will do the mean for a subset of trials
%Hits_included=[5];

%% Get the raw and inferred traces generated by drgCaimAn_script
[fnameca,pnameca,nCancel] = uigetfile({'*_pre_per.mat'},'Select the output file from drgCaimAn_dropc...');
if nCancel
    inputPath = [pnameca,fnameca];
    pnameStart = pnameca;
    %save('timeCorr_cfg.mat','pnameStart','-append');
else
    error('Cancelled')
end

CaimAn_name=[pnameca fnameca];

load(CaimAn_name)

bkg_from=1;
bkg_to=44;

%Calculate mean dFF
szHit_traces=size(Hit_traces);
Hit_trials=szHit_traces(1)/no_traces;
if exist('Hits_included')==0
    Hit_mask=ones(1,szHit_traces(1));
else
    Hit_mask=zeros(1,szHit_traces(1));
    for ii=1:Hit_trials
        if sum(Hits_included==ii)>0
            Hit_mask((ii-1)*no_traces+1:ii*no_traces)=1; 
        end
    end
end

dFF_mean_Hit=zeros(no_traces,szHit_traces(2));
max_dFF_Hit=zeros(no_traces,1);

figure(1)
hold on
for traceNo=1:no_traces
    dFF_mean_Hit(traceNo,:)=mean(Hit_traces((which_trace_Hit==traceNo)&(Hit_mask==1),:),1);
    plot(dFF_mean_Hit(traceNo,:))
%     dFF_mean_Hit(traceNo,:)=dFF_mean_Hit(traceNo,:)/std(dFF_mean_Hit(traceNo,bkg_from:bkg_to),0,2);
    dFF_mean_Hit(traceNo,:)=dFF_mean_Hit(traceNo,:)/mean(dFF_mean_Hit(traceNo,bkg_from:bkg_to),2);
    max_dFF_Hit(traceNo,1)=max(dFF_mean_Hit(traceNo,:));
end

%CR
szCR_traces=size(CR_traces);
dFF_mean_CR=zeros(no_traces,szCR_traces(2));
max_dFF_CR=zeros(no_traces,1);
for traceNo=1:no_traces
    dFF_mean_CR(traceNo,:)=mean(CR_traces(which_trace_CR==traceNo,:),1);
    dFF_mean_CR(traceNo,:)=dFF_mean_CR(traceNo,:)/mean(dFF_mean_CR(traceNo,bkg_from:bkg_to),2);
    max_dFF_CR(traceNo,1)=max(dFF_mean_CR(traceNo,:));
end

%FA
szFA_traces=size(FA_traces);
dFF_mean_FA=zeros(no_traces,szFA_traces(2));
max_dFF_FA=zeros(no_traces,1);
for traceNo=1:no_traces
    dFF_mean_FA(traceNo,:)=mean(FA_traces(which_trace_FA==traceNo,:),1);
    dFF_mean_FA(traceNo,:)=dFF_mean_FA(traceNo,:)/mean(dFF_mean_FA(traceNo,bkg_from:bkg_to),2);
    max_dFF_FA(traceNo,1)=max(dFF_mean_FA(traceNo,:));
end

%Miss
szMiss_traces=size(Miss_traces);
dFF_mean_Miss=zeros(no_traces,szMiss_traces(2));
max_dFF_Miss=zeros(no_traces,1);
for traceNo=1:no_traces
    dFF_mean_Miss(traceNo,:)=mean(Miss_traces(which_trace_Miss==traceNo,:),1);
    dFF_mean_Miss(traceNo,:)=dFF_mean_Miss(traceNo,:)/mean(dFF_mean_Miss(traceNo,bkg_from:bkg_to),2);
    max_dFF_Miss(traceNo,1)=max(dFF_mean_Miss(traceNo,:));
end

mindFF=min([prctile(dFF_mean_Miss(:),1) prctile(dFF_mean_CR(:),1) prctile(dFF_mean_FA(:),1) prctile(dFF_mean_Hit(:),1)]);
maxdFF=max([prctile(dFF_mean_Miss(:),99) prctile(dFF_mean_CR(:),99) prctile(dFF_mean_FA(:),99) prctile(dFF_mean_Hit(:),99)]);

%Do pseudocolor for Hits
try
    close 1
catch
end

hFig1 = figure(1);
set(hFig1, 'units','normalized','position',[.05 .2 .25 .7])


tr_index=[1:no_traces]';

to_be_sorted=[tr_index max_dFF_Hit];
sorted_out=sortrows(to_be_sorted,2);

transposed_dFF_mean_Hit=zeros(no_traces,szHit_traces(2));
for traceNo=1:no_traces
    transposed_dFF_mean_Hit(traceNo,:)=dFF_mean_Hit(sorted_out(traceNo,1),:);
end

time=repmat(time_to_eventHit,no_traces,1);
traces=repmat(tr_index,1,szHit_traces(2));


drg_pcolor(time,traces,transposed_dFF_mean_Hit)


colormap hot
shading interp
caxis([mindFF maxdFF]);
xlabel('Time (sec)')
ylabel('ROI');
title('delta F/F vs time for all ROIs Hit')
    
%Do pseudocolor for CR
try
    close 2
catch
end

hFig2 = figure(2);
set(hFig2, 'units','normalized','position',[.05 .2 .25 .7])


transposed_dFF_mean_CR=zeros(no_traces,szCR_traces(2));
for traceNo=1:no_traces
    transposed_dFF_mean_CR(traceNo,:)=dFF_mean_CR(sorted_out(traceNo,1),:);
end

time=repmat(time_to_eventCR,no_traces,1);
traces=repmat(tr_index,1,szCR_traces(2));


drg_pcolor(time,traces,transposed_dFF_mean_CR)


colormap jet
shading interp
caxis([mindFF maxdFF]);
xlabel('Time (sec)')
ylabel('ROI');
title('delta F/F vs time for all ROIs for CR')

%Do pseudocolor for FA
try
    close 3
catch
end

hFig3 = figure(3);
set(hFig3, 'units','normalized','position',[.05 .2 .25 .7])


transposed_dFF_mean_FA=zeros(no_traces,szFA_traces(2));
for traceNo=1:no_traces
    transposed_dFF_mean_FA(traceNo,:)=dFF_mean_FA(sorted_out(traceNo,1),:);
end

time=repmat(time_to_eventFA,no_traces,1);
traces=repmat(tr_index,1,szFA_traces(2));


drg_pcolor(time,traces,transposed_dFF_mean_FA)


colormap hot
shading interp
caxis([mindFF maxdFF]);
xlabel('Time (sec)')
ylabel('ROI');
title('delta F/F vs time for all ROIs for FA')

%Do pseudocolor for Miss
try
    close 4
catch
end

hFig4 = figure(4);
set(hFig4, 'units','normalized','position',[.05 .2 .25 .7])


transposed_dFF_mean_Miss=zeros(no_traces,szMiss_traces(2));
for traceNo=1:no_traces
    transposed_dFF_mean_Miss(traceNo,:)=dFF_mean_Miss(sorted_out(traceNo,1),:);
end

time=repmat(time_to_eventMiss,no_traces,1);
traces=repmat(tr_index,1,szMiss_traces(2));


drg_pcolor(time,traces,transposed_dFF_mean_Miss)


colormap hot
shading interp
caxis([mindFF maxdFF]);
xlabel('Time (sec)')
ylabel('ROI');
title('delta F/F vs time for all ROIs for Miss')
    


pffft=1;

