%% drgCaImAn_plot_traces.m
%
% Needs as an input the ouput file from drgCaImAn_dropc
%
close all
clear all

%% choices
plot_raw=1;
ref_win=[-5 -1.5];


%% Get the raw and inferred traces generated by drgCaimAn_script
[fnameca,pnameca,nCancel] = uigetfile({'*CalmAn.mat;*CalmAn_warped.mat'},'Select the output file from CaimAn...');
if nCancel
    inputPath = [pnameca,fnameca];
    pnameStart = pnameca;
    %save('timeCorr_cfg.mat','pnameStart','-append');
else
    error('Cancelled')
end


CaimAn_name=[pnameca fnameca];

load(CaimAn_name)
dt=1/options.fr;

[raw,inferred]=drgGetCAtraces(Yr,A_or,C_or,b2,f2,Cn,options);

% In order to understand what these variables are take a look at
% plot_components_GUI.m under CaImAn-MATLAB/utilities
% CaImAn calls ROIs "components"
% Yr hs the 6000 images in a vector of 65536 pixels
% A_or has the image of each component e.g. 65536x158 double for 256x256
% images of 85 components
% C_or these are the inferred traces for each component
% b2 are one or two images
% f2 are one or two traces
% Cn is the correlation image e.g. 256x256

% Should we use raw or inferred?
if plot_raw==1
    traces=raw;
else
    traces=inferred;
end
 
sz_traces=size(traces);
no_traces=sz_traces(1);
no_images=sz_traces(2);

fprintf(1, ['\ndrgCaImAn_dropc run for ' fnameca '\n\n']);

% Determine the y spacing of the traces
y_shift=1.2*(prctile(traces(:),95)-prctile(traces(:),5));

try
    close 1
catch
end

hFig1 = figure(1);
set(hFig1, 'units','normalized','position',[.05 .1 .85 .8])

hold on

%Plot the traces
time=[1:no_images]*dt;
for trNo=1:no_traces
% for trNo=1:20
    plot(time,traces(trNo,:)+y_shift*trNo,'-k','LineWidth',1)
end

ylim([-y_shift*0.2 (no_traces+2)*y_shift])
xlabel('time (s)')
ylabel('deltaF/F')
title(fnameca(1:end-4))

pffft=1;