%% drgCaimAndropcspmPerNeuron
% Caclulates per neuron traces of deltaF/F
% Requires as an input a file generated by drgCaImAn_dropc_plot.m
clear all
close all
warning('off','all')

% Load the file saved by drgCaImAn_dropc_plot
[fnamemp4,pnamemp4,nCancel] = uigetfile({'*_pre_per.mat'},'Select the optical flow estimate ...');
if nCancel
    inputPath = [pnamemp4,fnamemp4];
    pnameStart = pnamemp4;
    %save('timeCorr_cfg.mat','pnameStart','-append');
else
    error('Cancelled')
end

load(inputPath)


%Plot the Ca changes (this was calculated in drgCaImAn_dropc_plot)
figure(2)
hold on


%Odor on markers
plot([0 0],[0 max([max(mean(splus_traces(sp_odor_response==0,:),1)')+max(CIsp(:)) max(mean(sminus_traces(sm_odor_response==0,:),1)')+max(CIsm(:))])+3.5],'-k')
odorhl=plot([0 mean(delta_odor)],[0.45 0.45],'-k','LineWidth',5);
plot([mean(delta_odor) mean(delta_odor)],[0 max([max(mean(splus_traces(sp_odor_response==0,:),1)')+max(CIsp(:)) max(mean(sminus_traces(sm_odor_response==0,:),1)')+max(CIsm(:))])+3.5],'-k')

%Reinforcement markers
plot([mean(delta_odor_on_reinf_on) mean(delta_odor_on_reinf_on)],[0 max([max(mean(splus_traces(sp_odor_response==0,:),1)')+max(CIsp(:)) max(mean(sminus_traces(sm_odor_response==0,:),1)')+max(CIsm(:))])+3.5],'-r')
reinfhl=plot([mean(delta_odor_on_reinf_on) mean(delta_odor_on_reinf_on)+mean(delta_reinf)],[0.45 0.45],'-r','LineWidth',5);
plot([mean(delta_odor_on_reinf_on)+mean(delta_reinf) mean(delta_odor_on_reinf_on)+mean(delta_reinf)],[0 max([max(mean(splus_traces(sp_odor_response==0,:),1)')+max(CIsp(:)) max(mean(sminus_traces(sm_odor_response==0,:),1)')+max(CIsm(:))])+3.5],'-r')

if no_CR_traces>2
[hlCR, hpCR] = boundedline(time_to_eventCR',mean(CR_traces,1)', CICR', 'b');
end
if no_Hit_traces>2
[hlHit, hpHit] = boundedline(time_to_eventHit',mean(Hit_traces,1)', CIHit', 'r');
end
if no_Miss_traces>2
[hlMiss, hpMiss] = boundedline(time_to_eventMiss',mean(Miss_traces,1)', CIMiss', 'm');
end
if no_FA_traces>2
[hlFA, hpFA] = boundedline(time_to_eventFA',mean(FA_traces,1)', CIFA', 'c');
end

title("Ca changes aligned to odor onset")
if (no_Hit_traces>2)&(no_CR_traces>2)&(no_FA_traces>2)&(no_Miss_traces>2)
    legend([hlHit hlMiss hlCR hlFA],'Hit','Miss','CR','FA')
end

xlabel('Time (sec)')
ylabel('dF/F')
ylim([0 1.5])

%Now plot the Ca changes for each neuron (each trace)
all_Hit_traces=[];
maxHittraces=[];
noHits=0;

all_CR_traces=[];
maxCRtraces=[];
noCRs=0;

all_FA_traces=[];
maxFAtraces=[];
noFAs=0;

all_Miss_traces=[];
maxMisstraces=[];
noMisss=0;

for trNo=1:no_traces
    figNo=floor((trNo-1)/9)+3;
    subplotNo=trNo-9*floor((trNo-1)/9);
    figure(figNo)

    subplot(3,3,subplotNo)
    hold on
    
    
    %Odor on markers
    plot([0 0],[0 max([max(mean(splus_traces(sp_odor_response==0,:),1)')+max(CIsp(:)) max(mean(sminus_traces(sm_odor_response==0,:),1)')+max(CIsm(:))])+3.5],'-k')
    odorhl=plot([0 mean(delta_odor)],[0.45 0.45],'-k','LineWidth',5);
    plot([mean(delta_odor) mean(delta_odor)],[0 max([max(mean(splus_traces(sp_odor_response==0,:),1)')+max(CIsp(:)) max(mean(sminus_traces(sm_odor_response==0,:),1)')+max(CIsm(:))])+3.5],'-k')
    
    %Reinforcement markers
    plot([mean(delta_odor_on_reinf_on) mean(delta_odor_on_reinf_on)],[0 max([max(mean(splus_traces(sp_odor_response==0,:),1)')+max(CIsp(:)) max(mean(sminus_traces(sm_odor_response==0,:),1)')+max(CIsm(:))])+3.5],'-r')
    reinfhl=plot([mean(delta_odor_on_reinf_on) mean(delta_odor_on_reinf_on)+mean(delta_reinf)],[0.45 0.45],'-r','LineWidth',5);
    plot([mean(delta_odor_on_reinf_on)+mean(delta_reinf) mean(delta_odor_on_reinf_on)+mean(delta_reinf)],[0 max([max(mean(splus_traces(sp_odor_response==0,:),1)')+max(CIsp(:)) max(mean(sminus_traces(sm_odor_response==0,:),1)')+max(CIsm(:))])+3.5],'-r')
    
      if no_Miss_traces>1
        [hlMiss, hpMiss] = plot(time_to_eventMiss',mean(Miss_traces(which_trace_Miss==trNo,:),1)', '-m');
        noMisss=noMisss+1;
        allMisstraces(noMisss,:)=mean(Miss_traces(which_trace_Miss==trNo,:));
        maxMisstraces(noMisss)=max(mean(Miss_traces(which_trace_Miss==trNo,:)));
    end
    if no_FA_traces>1
        plot(time_to_eventFA',mean(FA_traces(which_trace_FA==trNo,:),1)',  '-c');
         noFAs=noFAs+1;
        allFAtraces(noFAs,:)=mean(FA_traces(which_trace_FA==trNo,:));
        maxFAtraces(noFAs)=max(mean(FA_traces(which_trace_FA==trNo,:)));
    end
    if no_CR_traces>2
        stdCR=repmat(std(CR_traces(which_trace_CR==trNo,:),0,1),2,1)';
        meanCR=mean(CR_traces(which_trace_CR==trNo,:),1)';
        boundedline(time_to_eventCR',meanCR, stdCR, 'b')
        %plot(time_to_eventCR',mean(CR_traces(which_trace_CR==trNo,:),1)',  '-b');
        noCRs=noCRs+1;
        allCRtraces(noCRs,:)=mean(CR_traces(which_trace_CR==trNo,:));
        maxCRtraces(noCRs)=max(mean(CR_traces(which_trace_CR==trNo,:)));
        pct95CR(noCRs)=prctile(meanCR,95);
        pct5CR(noCRs)=prctile(meanCR,5);
        norm_allCRtraces(noCRs,:)=(allCRtraces(noCRs,:)-pct5CR(noCRs))/(pct95CR(noCRs)-pct5CR(noCRs));
%         ii_resp=find(meanCR(time_to_eventCR>-2)>mean(meanCR((time_to_eventCR>-4)&(time_to_eventCR<-2)))+1.5*mean(stdCR((time_to_eventCR>-4)&(time_to_eventCR<-2)),1),1,'first');
%         ii_respCR(noCRs)=find(time_to_eventCR>-2,1,'first')+ii_resp;
    end
    if no_Hit_traces>2
        stdHit=repmat(std(Hit_traces(which_trace_Hit==trNo,:),0,1),2,1)';
        meanHit=mean(Hit_traces(which_trace_Hit==trNo,:),1)';
        boundedline(time_to_eventHit',meanHit, stdHit, 'r')
        %plot(time_to_eventHit',mean(Hit_traces(which_trace_Hit==trNo,:),1)', '-r');
        noHits=noHits+1;
        allHittraces(noHits,:)=mean(Hit_traces(which_trace_Hit==trNo,:));
        maxHittraces(noHits)=max(mean(Hit_traces(which_trace_Hit==trNo,:)));
        pct95Hit(noHits)=prctile(meanHit,95);
        pct5Hit(noHits)=prctile(meanHit,5);
        norm_allHittraces(noHits,:)=(allHittraces(noHits,:)-pct5Hit(noHits))/(pct95Hit(noHits)-pct5Hit(noHits));
        ii_resp=find(meanHit(time_to_eventHit>-2)>mean(meanHit((time_to_eventHit>-4)&(time_to_eventHit<-2)))+1.5*mean(stdHit((time_to_eventHit>-4)&(time_to_eventHit<-2)),1),1,'first');
        ii_respHit(noHits)=find(time_to_eventHit>-2,1,'first')+ii_resp;
    end
  
    
    title(["Neuron " num2str(trNo)])

    
    xlabel('Time (sec)')
    ylabel('dF/F')
    ylim([0 4])
    
end

if noCRs>1

    to_sort=[ii_respHit' norm_allCRtraces];
    sorted_mat=sortrows(to_sort,1);
    sorted_allCRtraces=sorted_mat(:,2:end);
    
    figNo=figNo+1;
    figure(figNo)
    drg_pcolor(repmat(time_to_eventCR,noCRs,1),repmat(1:noCRs,length(time_to_eventCR'),1)',sorted_allCRtraces)
    colormap jet
    shading flat
    
    hold on
    plot([0 0],[0 noCRs],'-k','LineWidth',2)
    plot([mean(delta_odor_on_reinf_on) mean(delta_odor_on_reinf_on)],[0 noCRs],'-r','LineWidth',2)
    title('CR Ca changes normalized and aligned to onset')
    xlabel('Time (sec)')
    
    
    to_sort=[pct95Hit' allCRtraces];
    sorted_mat=sortrows(to_sort,1);
    sorted_allCRtraces=sorted_mat(:,2:end);
    
    figNo=figNo+1;
    figure(figNo)
    drg_pcolor(repmat(time_to_eventCR,noCRs,1),repmat(1:noCRs,length(time_to_eventCR'),1)',sorted_allCRtraces)
    colormap jet
    shading flat
    
    hold on
    plot([0 0],[0 noCRs],'-k','LineWidth',2)
    plot([mean(delta_odor_on_reinf_on) mean(delta_odor_on_reinf_on)],[0 noCRs],'-r','LineWidth',2)
    title('CR Ca changes sorted by pct95(Hit)')
    xlabel('Time (sec)')
    
end

if noHits>1
    
    to_sort=[ii_respHit' norm_allHittraces];
    sorted_mat=sortrows(to_sort,1);
    sorted_allHittraces=sorted_mat(:,2:end);
    
    figNo=figNo+1;
    figure(figNo)
    drg_pcolor(repmat(time_to_eventHit,noHits,1),repmat(1:noHits,length(time_to_eventHit'),1)',sorted_allHittraces)
   % drg_pcolor(repmat(time_to_eventHit,noHits,1),repmat(1:noHits,length(time_to_eventHit'),1)',allHittraces)
    colormap jet
    shading flat
    
    hold on
    plot([0 0],[0 noHits],'-k','LineWidth',2)
    plot([mean(delta_odor_on_reinf_on) mean(delta_odor_on_reinf_on)],[0 noHits],'-r','LineWidth',2)
    title('Hit Ca changes normalized and aligned to onset')
    xlabel('Time (sec)')
    
     to_sort=[pct95Hit' allHittraces];
    sorted_mat=sortrows(to_sort,1);
    sorted_allHittraces=sorted_mat(:,2:end);
    
    figNo=figNo+1;
    figure(figNo)
    drg_pcolor(repmat(time_to_eventHit,noHits,1),repmat(1:noHits,length(time_to_eventHit'),1)',sorted_allHittraces)
   % drg_pcolor(repmat(time_to_eventHit,noHits,1),repmat(1:noHits,length(time_to_eventHit'),1)',allHittraces)
    colormap jet
    shading flat
    
    hold on
    plot([0 0],[0 noHits],'-k','LineWidth',2)
    plot([mean(delta_odor_on_reinf_on) mean(delta_odor_on_reinf_on)],[0 noHits],'-r','LineWidth',2)
    title('Hit Ca changes sorted by pct95(Hit)')
    xlabel('Time (sec)')
    
end
pffft=1