%This program generates a summary figure for the LDA analysis for Fig. 3
%This uses the output produced by drgCaImAnBatchPerSessionReversalPerTrialLDA
close all
clear all

dimesnionality=[];
glm_dim=[];
glm_dim_ii=0;
dim_stats=[];
dim_stats_ii=0;
no_comps=[];

%We use <65 (low) and >=80 (high) for mmPVG04

win_label{1}='Pre_odor';
win_label{2}='Odor';
win_label{3}='Reinforcement';

pcorr_label{1}='Naive';
pcorr_label{2}='Proficient';

%Note:This program uses files generated by drgCaImAnBatchPerSessionEventsPerTrialDimensionality
file_names{1}='/Users/restrepd/Documents/Projects/MOM slidebook/mmPVG04/20180910_mmPVG04_Cerebellum_new_analysis/20180910_mmPVG04_Cerebellum_dims.mat';

file_names{2}='/Users/restrepd/Documents/Projects/MOM slidebook/mmPVG05/20181017_mmPVG05_Cerebellum new analysis/20181017_19_mmPVG05_Cerebellum_out_dims.mat';

file_names{3}='/Users/restrepd/Documents/Projects/MOM slidebook/mmG7f09/20180702_mmG7f09-Cerebellum new analysis/20180702_05_mmG7f09-Cerebellum_out_dims.mat';

file_names{4}='/Users/restrepd/Documents/Projects/MOM slidebook/mmPVG02/20180515_mmPVG02_Cerebellum_new_analysis/20180515_18_mmPVG02_Cerebellum_out_dims.mat';


for fileNo=1:length(file_names)
    load(file_names{fileNo})
    ii_pc=0;
    no_comps(fileNo)=mean(dim_out.noROIs);
    fprintf(1, ['\n\nNumber of components for file No %d is %d\n'],fileNo,floor(no_comps(fileNo)))
    dim_stats_ii=0;
    for pcorr_ii=[1 3]
        ii_pc=ii_pc+1;
        for win=1:3
            dimensionality(ii_pc,win,fileNo)=dim_out.perCorr(pcorr_ii).window(win).dimensionality;
            glm_dim_ii=glm_dim_ii+1;
            glm_dim.data(glm_dim_ii)=dimensionality(ii_pc,win,fileNo);
            glm_dim.time_win(glm_dim_ii)=win;
            glm_dim.pcorr_win(glm_dim_ii)=ii_pc;
            dim_stats_ii=dim_stats_ii+1;
            dim_stats(dim_stats_ii).data(fileNo)=dimensionality(ii_pc,win,fileNo);
            dim_stats(dim_stats_ii).description=[pcorr_label{ii_pc} ' ' win_label{win}];
        end
    end
end

fprintf(1, ['\n\nMean number of components is %d, SD %d\n'],mean(no_comps),std(no_comps))


CIdimesnionality=zeros(ii_pc,3,2);
for pc_ii=1:ii_pc
    for win_ii=1:3
        these_dims=zeros(1,length(file_names));
        these_dims(1,:)=dimensionality(pc_ii,win_ii,:);
        CIdimesnionality(pc_ii,win_ii,:) = bootci(1000, {@mean, these_dims})';
    end
end

%Perform the glm for LDA percent correct 
fprintf(1, ['\n\nglm for LDA percent correct\n'])
tbl = table(glm_dim.data',glm_dim.time_win',glm_dim.pcorr_win',...
    'VariableNames',{'percent_correct_LDA','time_window','naive_proficient'});
mdl = fitglm(tbl,'percent_correct_LDA~time_window+naive_proficient+time_window*naive_proficient'...
    ,'CategoricalVars',[2,3])


% Do ranksum/t test
fprintf(1, ['\n\nRanksum or t-test p values for for LDA percent correct\n'])
try
    [output_data] = drgMutiRanksumorTtest(dim_stats);
    fprintf(1, '\n\n')
catch
end




try
    close 5
catch
end

hFig5 = figure(5);
set(hFig5, 'units','normalized','position',[.07 .7 .7 .3])
hold on

x_ii=1;
for pc_ii=1:ii_pc
    for win_ii=1:3
        this_dim=zeros(1,length(file_names));
        this_dim(1,:)=dimensionality(pc_ii,win_ii,:);
        if pc_ii==1
            bar(x_ii,mean(this_dim),'b')
        else
            bar(x_ii,mean(this_dim),'r')
        end
        this_CI=zeros(1,2);
        this_CI(1,:)=CIdimesnionality(pc_ii,win_ii,:);
        plot([x_ii x_ii],this_CI,'-k','LineWidth',3)
        x_ii=x_ii+1;
    end
    x_ii=x_ii+1;
end

%Plot the points
for ii=1:4
    %mmPVG04 is GCaMP6f
    plot([1 2 3],[dimensionality(1,1,1) dimensionality(1,2,1) dimensionality(1,3,1)],'-ok','MarkerSize',10)
    plot([5 6 7],[ dimensionality(2,1,1) dimensionality(2,2,1) dimensionality(2,3,1)],'-ok','MarkerSize',10)
    %mmPVG02 is GCaMP6s
    plot([1 2 3 ],[dimensionality(1,1,2) dimensionality(1,2,2) dimensionality(1,3,2) ],'-sk','MarkerSize',10)
    plot([5 6 7],[ dimensionality(2,1,2) dimensionality(2,2,2) dimensionality(2,3,2)],'-sk','MarkerSize',10)
    
    %mmG7f09 is GCaMP7f
    plot([1 2 3 ],[dimensionality(1,1,3) dimensionality(1,2,3) dimensionality(1,3,3) ],'-xk','MarkerSize',10)
    plot([5 6 7],[ dimensionality(2,1,3) dimensionality(2,2,3) dimensionality(2,3,3)],'-xk','MarkerSize',10)
    
    %mmPVG05 is GCaMP6f
    plot([1 2 3 ],[dimensionality(1,1,4) dimensionality(1,2,4) dimensionality(1,3,4) ],'-ok','MarkerSize',10)
    plot([5 6 7],[ dimensionality(2,1,4) dimensionality(2,2,4) dimensionality(2,3,4)],'-ok','MarkerSize',10)
end

xticks([1 2 3 5 6 7])
xticklabels({'pre-odor','odor','reinforcement','pre-odor','odor','reinforcement'})
ylim([1 7])
ylabel('Dimensionality')
text(1.5,6.5,'Learning')
text(5.5,6.5,'Proficient')
title('Dimensionality')




pffft=1;


